version: '0.1.3.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
  - develop
init:
  - cmd: git config --global core.autocrlf true
configuration:
  - Release
before_build:
  - cmd: dotnet --version
  - choco install redis-64
  - redis-server --service-install
  - redis-server --service-start
build_script:
  - cmd: dotnet build ./src/Nancy.RapidCache/Nancy.RapidCache.csproj -v quiet
  - cmd: dotnet build ./src/Nancy.RapidCache.Redis/Nancy.RapidCache.Redis.csproj -v quiet
  - cmd: dotnet publish ./src/Nancy.RapidCache/Nancy.RapidCache.csproj -v quiet -f=netstandard2.0
  - cmd: dotnet publish ./src/Nancy.RapidCache.Redis/Nancy.RapidCache.Redis.csproj -v quiet -f=netstandard2.0
test_script: 
  - cmd: dotnet test ./tests/Nancy.RapidCache.Tests.csproj -v quiet
artifacts:
  - path: '**/*.nupkg'
skip_commits:
  files:
    - '**/*.md'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/nancy-rapid-cache/api/v2/package
  on:
    branch: develop
    appveyor_repo_tag: true
  api_key:
    secure: 6xhHSsDvB9arsrSDLuynnbxaVS+BwaoJU96RfQenc5FOnUYvP8SHM6kbvrmpvja2
  skip_symbols: true
